
import 'package:ft/src/misc.dart' as Ft;

/* Classes */

class Instruction
{
  final int addr;
  final bool extended;
  final int opcode;
  final int operand;

  Instruction(
    this.addr,
    this.extended,
    this.opcode,
    this.operand
  );
}

class InstructionInfo
{

  final dynamic opCode;
  final String name;
  final int byteSize;
  final int durationSuccess;
  final int durationFail;
  final String flagInfo;

  InstructionInfo(
    this.opCode,
    this.name,
    this.byteSize,
    this.durationSuccess,
    this.durationFail,
    this.flagInfo
  );

  String toString(){
  return 
'''opCode: ${Ft.toAddressString(this.opCode.index, 2)} {
  name: ${this.name}
  byteSize: ${this.byteSize}
  durationSuccess: ${this.durationSuccess}
  durationFail: ${this.durationFail}
  flagInfo: ${this.flagInfo}
}''';
  }
}

/* Enums */

enum OpCode {
  NOP,
  LD_BC_d16,
  LD_i_BC_A,
  INC_BC,
  INC_B,
  DEC_B,
  LD_B_d8,
  RLCA,
  LD_i_a16_SP,
  ADD_HL_BC,
  LD_A_i_BC,
  DEC_BC,
  INC_C,
  DEC_C,
  LD_C_d8,
  RRCA,
  STOP_0,
  LD_DE_d16,
  LD_i_DE_A,
  INC_DE,
  INC_D,
  DEC_D,
  LD_D_d8,
  RLA,
  JR_r8,
  ADD_HL_DE,
  LD_A_i_DE,
  DEC_DE,
  INC_E,
  DEC_E,
  LD_E_d8,
  RRA,
  JR_NZ_r8,
  LD_HL_d16,
  LD_i_HLp_A,
  INC_HL,
  INC_H,
  DEC_H,
  LD_H_d8,
  DAA,
  JR_Z_r8,
  ADD_HL_HL,
  LD_A_i_HLp,
  DEC_HL,
  INC_L,
  DEC_L,
  LD_L_d8,
  CPL,
  JR_NC_r8,
  LD_SP_d16,
  LD_i_HLm_A,
  INC_SP,
  INC_i_HL,
  DEC_i_HL,
  LD_i_HL_d8,
  SCF,
  JR_C_r8,
  ADD_HL_SP,
  LD_A_i_HLm,
  DEC_SP,
  INC_A,
  DEC_A,
  LD_A_d8,
  CCF,
  LD_B_B,
  LD_B_C,
  LD_B_D,
  LD_B_E,
  LD_B_H,
  LD_B_L,
  LD_B_i_HL,
  LD_B_A,
  LD_C_B,
  LD_C_C,
  LD_C_D,
  LD_C_E,
  LD_C_H,
  LD_C_L,
  LD_C_i_HL,
  LD_C_A,
  LD_D_B,
  LD_D_C,
  LD_D_D,
  LD_D_E,
  LD_D_H,
  LD_D_L,
  LD_D_i_HL,
  LD_D_A,
  LD_E_B,
  LD_E_C,
  LD_E_D,
  LD_E_E,
  LD_E_H,
  LD_E_L,
  LD_E_i_HL,
  LD_E_A,
  LD_H_B,
  LD_H_C,
  LD_H_D,
  LD_H_E,
  LD_H_H,
  LD_H_L,
  LD_H_i_HL,
  LD_H_A,
  LD_L_B,
  LD_L_C,
  LD_L_D,
  LD_L_E,
  LD_L_H,
  LD_L_L,
  LD_L_i_HL,
  LD_L_A,
  LD_i_HL_B,
  LD_i_HL_C,
  LD_i_HL_D,
  LD_i_HL_E,
  LD_i_HL_H,
  LD_i_HL_L,
  HALT,
  LD_i_HL_A,
  LD_A_B,
  LD_A_C,
  LD_A_D,
  LD_A_E,
  LD_A_H,
  LD_A_L,
  LD_A_i_HL,
  LD_A_A,
  ADD_A_B,
  ADD_A_C,
  ADD_A_D,
  ADD_A_E,
  ADD_A_H,
  ADD_A_L,
  ADD_A_i_HL,
  ADD_A_A,
  ADC_A_B,
  ADC_A_C,
  ADC_A_D,
  ADC_A_E,
  ADC_A_H,
  ADC_A_L,
  ADC_A_i_HL,
  ADC_A_A,
  SUB_B,
  SUB_C,
  SUB_D,
  SUB_E,
  SUB_H,
  SUB_L,
  SUB_i_HL,
  SUB_A,
  SBC_A_B,
  SBC_A_C,
  SBC_A_D,
  SBC_A_E,
  SBC_A_H,
  SBC_A_L,
  SBC_A_i_HL,
  SBC_A_A,
  AND_B,
  AND_C,
  AND_D,
  AND_E,
  AND_H,
  AND_L,
  AND_i_HL,
  AND_A,
  XOR_B,
  XOR_C,
  XOR_D,
  XOR_E,
  XOR_H,
  XOR_L,
  XOR_i_HL,
  XOR_A,
  OR_B,
  OR_C,
  OR_D,
  OR_E,
  OR_H,
  OR_L,
  OR_i_HL,
  OR_A,
  CP_B,
  CP_C,
  CP_D,
  CP_E,
  CP_H,
  CP_L,
  CP_i_HL,
  CP_A,
  RET_NZ,
  POP_BC,
  JP_NZ_a16,
  JP_a16,
  CALL_NZ_a16,
  PUSH_BC,
  ADD_A_d8,
  RST_00H,
  RET_Z,
  RET,
  JP_Z_a16,
  CB_PREFIX,
  CALL_Z_a16,
  CALL_a16,
  ADC_A_d8,
  RST_08H,
  RET_NC,
  POP_DE,
  JP_NC_a16,
  D3_NA,
  CALL_NC_a16,
  PUSH_DE,
  SUB_d8,
  RST_10H,
  RET_C,
  RETI,
  JP_C_a16,
  DB_NA,
  CALL_C_a16,
  DD_NA,
  SBC_A_d8,
  RST_18H,
  LDH_i_a8_A,
  POP_HL,
  LD_i_C_A,
  E3_NA,
  E4_NA,
  PUSH_HL,
  AND_d8,
  RST_20H,
  ADD_SP_r8,
  JP_i_HL,
  LD_i_a16_A,
  EB_NA,
  EC_NA,
  ED_NA,
  XOR_d8,
  RST_28H,
  LDH_A_i_a8,
  POP_AF,
  LD_A_i_C,
  DI,
  F4_NA,
  PUSH_AF,
  OR_d8,
  RST_30H,
  LD_HL_SPpr8,
  LD_SP_HL,
  LD_A_i_a16,
  EI,
  FC_NA,
  FD_NA,
  CP_d8,
  RST_38H
}

enum EXOpCode {
  RLC_B,
  RLC_C,
  RLC_D,
  RLC_E,
  RLC_H,
  RLC_L,
  RLC_i_HL,
  RLC_A,
  RRC_B,
  RRC_C,
  RRC_D,
  RRC_E,
  RRC_H,
  RRC_L,
  RRC_i_HL,
  RRC_A,
  RL_B,
  RL_C,
  RL_D,
  RL_E,
  RL_H,
  RL_L,
  RL_i_HL,
  RL_A,
  RR_B,
  RR_C,
  RR_D,
  RR_E,
  RR_H,
  RR_L,
  RR_i_HL,
  RR_A,
  SLA_B,
  SLA_C,
  SLA_D,
  SLA_E,
  SLA_H,
  SLA_L,
  SLA_i_HL,
  SLA_A,
  SRA_B,
  SRA_C,
  SRA_D,
  SRA_E,
  SRA_H,
  SRA_L,
  SRA_i_HL,
  SRA_A,
  SWAP_B,
  SWAP_C,
  SWAP_D,
  SWAP_E,
  SWAP_H,
  SWAP_L,
  SWAP_i_HL,
  SWAP_A,
  SRL_B,
  SRL_C,
  SRL_D,
  SRL_E,
  SRL_H,
  SRL_L,
  SRL_i_HL,
  SRL_A,
  BIT_0_B,
  BIT_0_C,
  BIT_0_D,
  BIT_0_E,
  BIT_0_H,
  BIT_0_L,
  BIT_0_i_HL,
  BIT_0_A,
  BIT_1_B,
  BIT_1_C,
  BIT_1_D,
  BIT_1_E,
  BIT_1_H,
  BIT_1_L,
  BIT_1_i_HL,
  BIT_1_A,
  BIT_2_B,
  BIT_2_C,
  BIT_2_D,
  BIT_2_E,
  BIT_2_H,
  BIT_2_L,
  BIT_2_i_HL,
  BIT_2_A,
  BIT_3_B,
  BIT_3_C,
  BIT_3_D,
  BIT_3_E,
  BIT_3_H,
  BIT_3_L,
  BIT_3_i_HL,
  BIT_3_A,
  BIT_4_B,
  BIT_4_C,
  BIT_4_D,
  BIT_4_E,
  BIT_4_H,
  BIT_4_L,
  BIT_4_i_HL,
  BIT_4_A,
  BIT_5_B,
  BIT_5_C,
  BIT_5_D,
  BIT_5_E,
  BIT_5_H,
  BIT_5_L,
  BIT_5_i_HL,
  BIT_5_A,
  BIT_6_B,
  BIT_6_C,
  BIT_6_D,
  BIT_6_E,
  BIT_6_H,
  BIT_6_L,
  BIT_6_i_HL,
  BIT_6_A,
  BIT_7_B,
  BIT_7_C,
  BIT_7_D,
  BIT_7_E,
  BIT_7_H,
  BIT_7_L,
  BIT_7_i_HL,
  BIT_7_A,
  RES_0_B,
  RES_0_C,
  RES_0_D,
  RES_0_E,
  RES_0_H,
  RES_0_L,
  RES_0_i_HL,
  RES_0_A,
  RES_1_B,
  RES_1_C,
  RES_1_D,
  RES_1_E,
  RES_1_H,
  RES_1_L,
  RES_1_i_HL,
  RES_1_A,
  RES_2_B,
  RES_2_C,
  RES_2_D,
  RES_2_E,
  RES_2_H,
  RES_2_L,
  RES_2_i_HL,
  RES_2_A,
  RES_3_B,
  RES_3_C,
  RES_3_D,
  RES_3_E,
  RES_3_H,
  RES_3_L,
  RES_3_i_HL,
  RES_3_A,
  RES_4_B,
  RES_4_C,
  RES_4_D,
  RES_4_E,
  RES_4_H,
  RES_4_L,
  RES_4_i_HL,
  RES_4_A,
  RES_5_B,
  RES_5_C,
  RES_5_D,
  RES_5_E,
  RES_5_H,
  RES_5_L,
  RES_5_i_HL,
  RES_5_A,
  RES_6_B,
  RES_6_C,
  RES_6_D,
  RES_6_E,
  RES_6_H,
  RES_6_L,
  RES_6_i_HL,
  RES_6_A,
  RES_7_B,
  RES_7_C,
  RES_7_D,
  RES_7_E,
  RES_7_H,
  RES_7_L,
  RES_7_i_HL,
  RES_7_A,
  SET_0_B,
  SET_0_C,
  SET_0_D,
  SET_0_E,
  SET_0_H,
  SET_0_L,
  SET_0_i_HL,
  SET_0_A,
  SET_1_B,
  SET_1_C,
  SET_1_D,
  SET_1_E,
  SET_1_H,
  SET_1_L,
  SET_1_i_HL,
  SET_1_A,
  SET_2_B,
  SET_2_C,
  SET_2_D,
  SET_2_E,
  SET_2_H,
  SET_2_L,
  SET_2_i_HL,
  SET_2_A,
  SET_3_B,
  SET_3_C,
  SET_3_D,
  SET_3_E,
  SET_3_H,
  SET_3_L,
  SET_3_i_HL,
  SET_3_A,
  SET_4_B,
  SET_4_C,
  SET_4_D,
  SET_4_E,
  SET_4_H,
  SET_4_L,
  SET_4_i_HL,
  SET_4_A,
  SET_5_B,
  SET_5_C,
  SET_5_D,
  SET_5_E,
  SET_5_H,
  SET_5_L,
  SET_5_i_HL,
  SET_5_A,
  SET_6_B,
  SET_6_C,
  SET_6_D,
  SET_6_E,
  SET_6_H,
  SET_6_L,
  SET_6_i_HL,
  SET_6_A,
  SET_7_B,
  SET_7_C,
  SET_7_D,
  SET_7_E,
  SET_7_H,
  SET_7_L,
  SET_7_i_HL,
  SET_7_A
}

/* Global */

final instInfos = new List<InstructionInfo>.unmodifiable([
  new InstructionInfo(OpCode.NOP, 'NOP', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_BC_d16, 'LD BC,d16', 3, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.LD_i_BC_A, 'LD (BC),A', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_BC, 'INC BC', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_B, 'INC B', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_B, 'DEC B', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_B_d8, 'LD B,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.RLCA, 'RLCA', 1, 4, 4, '0 0 0 C'),
  new InstructionInfo(OpCode.LD_i_a16_SP, 'LD (a16),SP', 3, 20, 20, '- - - -'),
  new InstructionInfo(OpCode.ADD_HL_BC, 'ADD HL,BC', 1, 8, 8, '- 0 H C'),
  new InstructionInfo(OpCode.LD_A_i_BC, 'LD A,(BC)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.DEC_BC, 'DEC BC', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_C, 'INC C', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_C, 'DEC C', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_C_d8, 'LD C,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.RRCA, 'RRCA', 1, 4, 4, '0 0 0 C'),
  new InstructionInfo(OpCode.STOP_0, 'STOP 0', 2, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_DE_d16, 'LD DE,d16', 3, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.LD_i_DE_A, 'LD (DE),A', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_DE, 'INC DE', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_D, 'INC D', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_D, 'DEC D', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_D_d8, 'LD D,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.RLA, 'RLA', 1, 4, 4, '0 0 0 C'),
  new InstructionInfo(OpCode.JR_r8, 'JR r8', 2, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.ADD_HL_DE, 'ADD HL,DE', 1, 8, 8, '- 0 H C'),
  new InstructionInfo(OpCode.LD_A_i_DE, 'LD A,(DE)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.DEC_DE, 'DEC DE', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_E, 'INC E', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_E, 'DEC E', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_E_d8, 'LD E,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.RRA, 'RRA', 1, 4, 4, '0 0 0 C'),
  new InstructionInfo(OpCode.JR_NZ_r8, 'JR NZ,r8', 2, 12, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_HL_d16, 'LD HL,d16', 3, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HLp_A, 'LD (HL+),A', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_HL, 'INC HL', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_H, 'INC H', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_H, 'DEC H', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_H_d8, 'LD H,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.DAA, 'DAA', 1, 4, 4, 'Z - 0 C'),
  new InstructionInfo(OpCode.JR_Z_r8, 'JR Z,r8', 2, 12, 8, '- - - -'),
  new InstructionInfo(OpCode.ADD_HL_HL, 'ADD HL,HL', 1, 8, 8, '- 0 H C'),
  new InstructionInfo(OpCode.LD_A_i_HLp, 'LD A,(HL+)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.DEC_HL, 'DEC HL', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_L, 'INC L', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_L, 'DEC L', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_L_d8, 'LD L,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.CPL, 'CPL', 1, 4, 4, '- 1 1 -'),
  new InstructionInfo(OpCode.JR_NC_r8, 'JR NC,r8', 2, 12, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_SP_d16, 'LD SP,d16', 3, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HLm_A, 'LD (HL-),A', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_SP, 'INC SP', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_i_HL, 'INC (HL)', 1, 12, 12, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_i_HL, 'DEC (HL)', 1, 12, 12, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_i_HL_d8, 'LD (HL),d8', 2, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.SCF, 'SCF', 1, 4, 4, '- 0 0 1'),
  new InstructionInfo(OpCode.JR_C_r8, 'JR C,r8', 2, 12, 8, '- - - -'),
  new InstructionInfo(OpCode.ADD_HL_SP, 'ADD HL,SP', 1, 8, 8, '- 0 H C'),
  new InstructionInfo(OpCode.LD_A_i_HLm, 'LD A,(HL-)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.DEC_SP, 'DEC SP', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.INC_A, 'INC A', 1, 4, 4, 'Z 0 H -'),
  new InstructionInfo(OpCode.DEC_A, 'DEC A', 1, 4, 4, 'Z 1 H -'),
  new InstructionInfo(OpCode.LD_A_d8, 'LD A,d8', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.CCF, 'CCF', 1, 4, 4, '- 0 0 C'),
  new InstructionInfo(OpCode.LD_B_B, 'LD B,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_B_C, 'LD B,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_B_D, 'LD B,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_B_E, 'LD B,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_B_H, 'LD B,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_B_L, 'LD B,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_B_i_HL, 'LD B,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_B_A, 'LD B,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_B, 'LD C,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_C, 'LD C,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_D, 'LD C,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_E, 'LD C,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_H, 'LD C,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_L, 'LD C,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_C_i_HL, 'LD C,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_C_A, 'LD C,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_B, 'LD D,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_C, 'LD D,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_D, 'LD D,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_E, 'LD D,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_H, 'LD D,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_L, 'LD D,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_D_i_HL, 'LD D,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_D_A, 'LD D,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_B, 'LD E,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_C, 'LD E,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_D, 'LD E,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_E, 'LD E,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_H, 'LD E,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_L, 'LD E,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_E_i_HL, 'LD E,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_E_A, 'LD E,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_B, 'LD H,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_C, 'LD H,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_D, 'LD H,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_E, 'LD H,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_H, 'LD H,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_L, 'LD H,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_H_i_HL, 'LD H,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_H_A, 'LD H,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_B, 'LD L,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_C, 'LD L,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_D, 'LD L,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_E, 'LD L,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_H, 'LD L,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_L, 'LD L,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_L_i_HL, 'LD L,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_L_A, 'LD L,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_B, 'LD (HL),B', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_C, 'LD (HL),C', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_D, 'LD (HL),D', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_E, 'LD (HL),E', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_H, 'LD (HL),H', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_L, 'LD (HL),L', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.HALT, 'HALT', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_i_HL_A, 'LD (HL),A', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_A_B, 'LD A,B', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_A_C, 'LD A,C', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_A_D, 'LD A,D', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_A_E, 'LD A,E', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_A_H, 'LD A,H', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_A_L, 'LD A,L', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_A_i_HL, 'LD A,(HL)', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_A_A, 'LD A,A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.ADD_A_B, 'ADD A,B', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_C, 'ADD A,C', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_D, 'ADD A,D', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_E, 'ADD A,E', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_H, 'ADD A,H', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_L, 'ADD A,L', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_i_HL, 'ADD A,(HL)', 1, 8, 8, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADD_A_A, 'ADD A,A', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_B, 'ADC A,B', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_C, 'ADC A,C', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_D, 'ADC A,D', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_E, 'ADC A,E', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_H, 'ADC A,H', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_L, 'ADC A,L', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_i_HL, 'ADC A,(HL)', 1, 8, 8, 'Z 0 H C'),
  new InstructionInfo(OpCode.ADC_A_A, 'ADC A,A', 1, 4, 4, 'Z 0 H C'),
  new InstructionInfo(OpCode.SUB_B, 'SUB B', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_C, 'SUB C', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_D, 'SUB D', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_E, 'SUB E', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_H, 'SUB H', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_L, 'SUB L', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_i_HL, 'SUB (HL)', 1, 8, 8, 'Z 1 H C'),
  new InstructionInfo(OpCode.SUB_A, 'SUB A', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_B, 'SBC A,B', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_C, 'SBC A,C', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_D, 'SBC A,D', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_E, 'SBC A,E', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_H, 'SBC A,H', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_L, 'SBC A,L', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_i_HL, 'SBC A,(HL)', 1, 8, 8, 'Z 1 H C'),
  new InstructionInfo(OpCode.SBC_A_A, 'SBC A,A', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.AND_B, 'AND B', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_C, 'AND C', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_D, 'AND D', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_E, 'AND E', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_H, 'AND H', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_L, 'AND L', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_i_HL, 'AND (HL)', 1, 8, 8, 'Z 0 1 0'),
  new InstructionInfo(OpCode.AND_A, 'AND A', 1, 4, 4, 'Z 0 1 0'),
  new InstructionInfo(OpCode.XOR_B, 'XOR B', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_C, 'XOR C', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_D, 'XOR D', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_E, 'XOR E', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_H, 'XOR H', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_L, 'XOR L', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_i_HL, 'XOR (HL)', 1, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(OpCode.XOR_A, 'XOR A', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_B, 'OR B', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_C, 'OR C', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_D, 'OR D', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_E, 'OR E', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_H, 'OR H', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_L, 'OR L', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_i_HL, 'OR (HL)', 1, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(OpCode.OR_A, 'OR A', 1, 4, 4, 'Z 0 0 0'),
  new InstructionInfo(OpCode.CP_B, 'CP B', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_C, 'CP C', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_D, 'CP D', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_E, 'CP E', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_H, 'CP H', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_L, 'CP L', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_i_HL, 'CP (HL)', 1, 8, 8, 'Z 1 H C'),
  new InstructionInfo(OpCode.CP_A, 'CP A', 1, 4, 4, 'Z 1 H C'),
  new InstructionInfo(OpCode.RET_NZ, 'RET NZ', 1, 20, 8, '- - - -'),
  new InstructionInfo(OpCode.POP_BC, 'POP BC', 1, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.JP_NZ_a16, 'JP NZ,a16', 3, 16, 12, '- - - -'),
  new InstructionInfo(OpCode.JP_a16, 'JP a16', 3, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.CALL_NZ_a16, 'CALL NZ,a16', 3, 24, 12, '- - - -'),
  new InstructionInfo(OpCode.PUSH_BC, 'PUSH BC', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.ADD_A_d8, 'ADD A,d8', 2, 8, 8, 'Z 0 H C'),
  new InstructionInfo(OpCode.RST_00H, 'RST 00H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.RET_Z, 'RET Z', 1, 20, 8, '- - - -'),
  new InstructionInfo(OpCode.RET, 'RET', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.JP_Z_a16, 'JP Z,a16', 3, 16, 12, '- - - -'),
  new InstructionInfo(OpCode.CB_PREFIX, '0xCB: PREFIX', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.CALL_Z_a16, 'CALL Z,a16', 3, 24, 12, '- - - -'),
  new InstructionInfo(OpCode.CALL_a16, 'CALL a16', 3, 24, 24, '- - - -'),
  new InstructionInfo(OpCode.ADC_A_d8, 'ADC A,d8', 2, 8, 8, 'Z 0 H C'),
  new InstructionInfo(OpCode.RST_08H, 'RST 08H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.RET_NC, 'RET NC', 1, 20, 8, '- - - -'),
  new InstructionInfo(OpCode.POP_DE, 'POP DE', 1, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.JP_NC_a16, 'JP NC,a16', 3, 16, 12, '- - - -'),
  new InstructionInfo(OpCode.D3_NA, '0xD3: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.CALL_NC_a16, 'CALL NC,a16', 3, 24, 12, '- - - -'),
  new InstructionInfo(OpCode.PUSH_DE, 'PUSH DE', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.SUB_d8, 'SUB d8', 2, 8, 8, 'Z 1 H C'),
  new InstructionInfo(OpCode.RST_10H, 'RST 10H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.RET_C, 'RET C', 1, 20, 8, '- - - -'),
  new InstructionInfo(OpCode.RETI, 'RETI', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.JP_C_a16, 'JP C,a16', 3, 16, 12, '- - - -'),
  new InstructionInfo(OpCode.DB_NA, '0xDB: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.CALL_C_a16, 'CALL C,a16', 3, 24, 12, '- - - -'),
  new InstructionInfo(OpCode.DD_NA, '0xDD: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.SBC_A_d8, 'SBC A,d8', 2, 8, 8, 'Z 1 H C'),
  new InstructionInfo(OpCode.RST_18H, 'RST 18H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.LDH_i_a8_A, 'LDH (a8),A', 2, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.POP_HL, 'POP HL', 1, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.LD_i_C_A, 'LD (C),A', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.E3_NA, '0xE3: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.E4_NA, '0xE4: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.PUSH_HL, 'PUSH HL', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.AND_d8, 'AND d8', 2, 8, 8, 'Z 0 1 0'),
  new InstructionInfo(OpCode.RST_20H, 'RST 20H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.ADD_SP_r8, 'ADD SP,r8', 2, 16, 16, '0 0 H C'),
  new InstructionInfo(OpCode.JP_i_HL, 'JP (HL)', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.LD_i_a16_A, 'LD (a16),A', 3, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.EB_NA, '0xEB: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.EC_NA, '0xEC: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.ED_NA, '0xED: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.XOR_d8, 'XOR d8', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(OpCode.RST_28H, 'RST 28H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.LDH_A_i_a8, 'LDH A,(a8)', 2, 12, 12, '- - - -'),
  new InstructionInfo(OpCode.POP_AF, 'POP AF', 1, 12, 12, 'Z N H C'),
  new InstructionInfo(OpCode.LD_A_i_C, 'LD A,(C)', 2, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.DI, 'DI', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.F4_NA, '0xF4: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.PUSH_AF, 'PUSH AF', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.OR_d8, 'OR d8', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(OpCode.RST_30H, 'RST 30H', 1, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.LD_HL_SPpr8, 'LD HL,SP+r8', 2, 12, 12, '0 0 H C'),
  new InstructionInfo(OpCode.LD_SP_HL, 'LD SP,HL', 1, 8, 8, '- - - -'),
  new InstructionInfo(OpCode.LD_A_i_a16, 'LD A,(a16)', 3, 16, 16, '- - - -'),
  new InstructionInfo(OpCode.EI, 'EI', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.FC_NA, '0xFC: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.FD_NA, '0xFD: N/A', 1, 4, 4, '- - - -'),
  new InstructionInfo(OpCode.CP_d8, 'CP d8', 2, 8, 8, 'Z 1 H C'),
  new InstructionInfo(OpCode.RST_38H, 'RST 38H', 1, 16, 16, '- - - -')
]);

final EXinstInfos = new List<InstructionInfo>.unmodifiable([
  new InstructionInfo(EXOpCode.RLC_B, 'RLC B', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_C, 'RLC C', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_D, 'RLC D', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_E, 'RLC E', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_H, 'RLC H', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_L, 'RLC L', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_i_HL, 'RLC (HL)', 2, 16, 16, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RLC_A, 'RLC A', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_B, 'RRC B', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_C, 'RRC C', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_D, 'RRC D', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_E, 'RRC E', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_H, 'RRC H', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_L, 'RRC L', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_i_HL, 'RRC (HL)', 2, 16, 16, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RRC_A, 'RRC A', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_B, 'RL B', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_C, 'RL C', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_D, 'RL D', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_E, 'RL E', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_H, 'RL H', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_L, 'RL L', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_i_HL, 'RL (HL)', 2, 16, 16, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RL_A, 'RL A', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_B, 'RR B', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_C, 'RR C', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_D, 'RR D', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_E, 'RR E', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_H, 'RR H', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_L, 'RR L', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_i_HL, 'RR (HL)', 2, 16, 16, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.RR_A, 'RR A', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_B, 'SLA B', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_C, 'SLA C', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_D, 'SLA D', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_E, 'SLA E', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_H, 'SLA H', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_L, 'SLA L', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_i_HL, 'SLA (HL)', 2, 16, 16, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SLA_A, 'SLA A', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRA_B, 'SRA B', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_C, 'SRA C', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_D, 'SRA D', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_E, 'SRA E', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_H, 'SRA H', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_L, 'SRA L', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_i_HL, 'SRA (HL)', 2, 16, 16, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRA_A, 'SRA A', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_B, 'SWAP B', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_C, 'SWAP C', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_D, 'SWAP D', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_E, 'SWAP E', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_H, 'SWAP H', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_L, 'SWAP L', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_i_HL, 'SWAP (HL)', 2, 16, 16, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SWAP_A, 'SWAP A', 2, 8, 8, 'Z 0 0 0'),
  new InstructionInfo(EXOpCode.SRL_B, 'SRL B', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_C, 'SRL C', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_D, 'SRL D', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_E, 'SRL E', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_H, 'SRL H', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_L, 'SRL L', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_i_HL, 'SRL (HL)', 2, 16, 16, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.SRL_A, 'SRL A', 2, 8, 8, 'Z 0 0 C'),
  new InstructionInfo(EXOpCode.BIT_0_B, 'BIT 0,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_C, 'BIT 0,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_D, 'BIT 0,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_E, 'BIT 0,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_H, 'BIT 0,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_L, 'BIT 0,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_i_HL, 'BIT 0,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_0_A, 'BIT 0,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_B, 'BIT 1,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_C, 'BIT 1,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_D, 'BIT 1,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_E, 'BIT 1,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_H, 'BIT 1,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_L, 'BIT 1,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_i_HL, 'BIT 1,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_1_A, 'BIT 1,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_B, 'BIT 2,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_C, 'BIT 2,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_D, 'BIT 2,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_E, 'BIT 2,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_H, 'BIT 2,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_L, 'BIT 2,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_i_HL, 'BIT 2,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_2_A, 'BIT 2,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_B, 'BIT 3,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_C, 'BIT 3,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_D, 'BIT 3,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_E, 'BIT 3,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_H, 'BIT 3,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_L, 'BIT 3,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_i_HL, 'BIT 3,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_3_A, 'BIT 3,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_B, 'BIT 4,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_C, 'BIT 4,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_D, 'BIT 4,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_E, 'BIT 4,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_H, 'BIT 4,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_L, 'BIT 4,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_i_HL, 'BIT 4,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_4_A, 'BIT 4,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_B, 'BIT 5,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_C, 'BIT 5,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_D, 'BIT 5,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_E, 'BIT 5,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_H, 'BIT 5,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_L, 'BIT 5,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_i_HL, 'BIT 5,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_5_A, 'BIT 5,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_B, 'BIT 6,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_C, 'BIT 6,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_D, 'BIT 6,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_E, 'BIT 6,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_H, 'BIT 6,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_L, 'BIT 6,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_i_HL, 'BIT 6,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_6_A, 'BIT 6,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_B, 'BIT 7,B', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_C, 'BIT 7,C', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_D, 'BIT 7,D', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_E, 'BIT 7,E', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_H, 'BIT 7,H', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_L, 'BIT 7,L', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_i_HL, 'BIT 7,(HL)', 2, 16, 16, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.BIT_7_A, 'BIT 7,A', 2, 8, 8, 'Z 0 1 -'),
  new InstructionInfo(EXOpCode.RES_0_B, 'RES 0,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_C, 'RES 0,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_D, 'RES 0,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_E, 'RES 0,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_H, 'RES 0,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_L, 'RES 0,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_i_HL, 'RES 0,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_0_A, 'RES 0,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_B, 'RES 1,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_C, 'RES 1,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_D, 'RES 1,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_E, 'RES 1,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_H, 'RES 1,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_L, 'RES 1,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_i_HL, 'RES 1,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_1_A, 'RES 1,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_B, 'RES 2,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_C, 'RES 2,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_D, 'RES 2,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_E, 'RES 2,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_H, 'RES 2,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_L, 'RES 2,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_i_HL, 'RES 2,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_2_A, 'RES 2,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_B, 'RES 3,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_C, 'RES 3,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_D, 'RES 3,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_E, 'RES 3,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_H, 'RES 3,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_L, 'RES 3,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_i_HL, 'RES 3,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_3_A, 'RES 3,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_B, 'RES 4,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_C, 'RES 4,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_D, 'RES 4,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_E, 'RES 4,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_H, 'RES 4,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_L, 'RES 4,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_i_HL, 'RES 4,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_4_A, 'RES 4,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_B, 'RES 5,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_C, 'RES 5,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_D, 'RES 5,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_E, 'RES 5,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_H, 'RES 5,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_L, 'RES 5,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_i_HL, 'RES 5,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_5_A, 'RES 5,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_B, 'RES 6,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_C, 'RES 6,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_D, 'RES 6,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_E, 'RES 6,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_H, 'RES 6,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_L, 'RES 6,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_i_HL, 'RES 6,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_6_A, 'RES 6,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_B, 'RES 7,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_C, 'RES 7,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_D, 'RES 7,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_E, 'RES 7,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_H, 'RES 7,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_L, 'RES 7,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_i_HL, 'RES 7,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.RES_7_A, 'RES 7,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_B, 'SET 0,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_C, 'SET 0,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_D, 'SET 0,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_E, 'SET 0,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_H, 'SET 0,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_L, 'SET 0,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_i_HL, 'SET 0,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_0_A, 'SET 0,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_B, 'SET 1,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_C, 'SET 1,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_D, 'SET 1,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_E, 'SET 1,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_H, 'SET 1,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_L, 'SET 1,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_i_HL, 'SET 1,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_1_A, 'SET 1,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_B, 'SET 2,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_C, 'SET 2,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_D, 'SET 2,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_E, 'SET 2,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_H, 'SET 2,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_L, 'SET 2,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_i_HL, 'SET 2,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_2_A, 'SET 2,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_B, 'SET 3,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_C, 'SET 3,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_D, 'SET 3,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_E, 'SET 3,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_H, 'SET 3,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_L, 'SET 3,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_i_HL, 'SET 3,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_3_A, 'SET 3,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_B, 'SET 4,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_C, 'SET 4,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_D, 'SET 4,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_E, 'SET 4,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_H, 'SET 4,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_L, 'SET 4,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_i_HL, 'SET 4,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_4_A, 'SET 4,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_B, 'SET 5,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_C, 'SET 5,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_D, 'SET 5,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_E, 'SET 5,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_H, 'SET 5,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_L, 'SET 5,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_i_HL, 'SET 5,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_5_A, 'SET 5,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_B, 'SET 6,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_C, 'SET 6,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_D, 'SET 6,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_E, 'SET 6,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_H, 'SET 6,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_L, 'SET 6,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_i_HL, 'SET 6,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_6_A, 'SET 6,A', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_B, 'SET 7,B', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_C, 'SET 7,C', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_D, 'SET 7,D', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_E, 'SET 7,E', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_H, 'SET 7,H', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_L, 'SET 7,L', 2, 8, 8, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_i_HL, 'SET 7,(HL)', 2, 16, 16, '- - - -'),
  new InstructionInfo(EXOpCode.SET_7_A, 'SET 7,A', 2, 8, 8, '- - - -')
]);

/* Debug */

// void debug()
// {
//   for (var info in instInfos)
//   {
//     assert (instInfos.indexOf(info) == info.opCode.index);
//     print(info);
//   }
// }

// void debugEX()
// {
//   for (var info in EXinstInfos)
//   {
//     assert (EXinstInfos.indexOf(info) == info.opCode.index);
//     print(info);
//   }
// }

// void main ()
// {
//   debug();
//   debugEX();
// }
